import type { AiStreamChunkPayload, AiAnalyzeResult, Locale, IconPackColorMode, TerminalPreferences, ExternalApplicationPreferences, EnvironmentPreferences, ProjectLaunchServicePreferences, ProjectLaunchServiceStatus, ProjectLaunchServiceLogRetentionStatus, EnvironmentToolDefinition, EnvironmentToolResult, AiPreferences, AiModelInfo, ProjectFormValue, UiPreferences, IconPackManifest, IconPackStatus, Project, WorkActivityPreferences, ProjectGitActivityReport, LogEntry, ProjectGitFileChange, ProjectGitSnapshot, ProjectGitReadOperation, ProjectGitReadFailure, ProjectGitWorkspaceSnapshot, TodoItem, ProjectAutomationPlanEntry, ProjectAutomationHistoryEntry, IconPackLoadResult, IconPackUpdateResult, IconPackRemoveResult, ProjectLaunchServiceEvent, ProjectLaunchServiceLogRetentionPolicy, ProjectLaunchServiceLogDescriptor, ProjectLaunchServiceLogClearScope, ProjectLaunchServiceLogClearResult, ProjectLaunchServiceAutomationSyncResult, TinyCardActionTrigger, DefaultTerminalKind, EnvironmentToolKey, CustomEnvironmentTool, BuiltinEnvironmentToolOverride, AiPromptMode, AiModelTestResult, ProjectGitActivityOptions, ProjectGitActivityChangesOptions, ProjectGitActivityChangesReport, ProjectGitActivityDayOptions, ProjectGitActivityDayReport, ProjectScriptDiscoverySource, ProjectBridgeScriptCandidate, ProjectEnvironmentEntry, ProjectScriptFormValue, ProjectGitRepositoryTarget, ProjectGitRepositoryContext, ProjectFileListResult, ProjectFileSearchResult, ProjectFileKind, ProjectFileMutationResult, ProjectFileReadResult, ProjectGitFileDiffOptions, ProjectGitFileDiffResult, ProjectGitStash, ProjectGitTagInfo, ProjectGitCommitMessageDiffResult, ProjectGitActionResult, ProjectGitStashOptions, ProjectGitPushOptions, ProjectGitMergeResult, ProjectFileWriteResult, ProjectAutomationTask, ProjectAutomationHistoryStatus, ProjectAutomationScriptResult, ProjectAutomationInputStep, ProjectAutomationExitConfig, ProjectBridgeEvent, ProjectBridgeRunResult, ProjectBridgeStopProcessOptions, ProjectBridgeSendInputResult } from "../types";
import type { CustomEnvironmentToolInput } from "../lib/environmentTools";
import { AutomationScriptRuntimeContext } from "./helpers/automationHelpers";
import type { Store } from "pinia";

export type AiAnalysisState = "idle" | "loading" | "success" | "warning" | "error";

export interface AiStreamHandlers {
  onStart?: () => void;
  onChunk?: (chunk: AiStreamChunkPayload) => void;
  onDone?: (result: AiAnalyzeResult) => void;
}

export interface AppState {
  locale: Locale;
  activeTab: "projects" | "settings" | "environment" | "activity";
  theme: "auto" | "light" | "dark";
  iconPackColorMode: IconPackColorMode;
  terminalPreferences: TerminalPreferences;
  externalApplicationPreferences: ExternalApplicationPreferences;
  environmentPreferences: EnvironmentPreferences;
  projectLaunchServicePreferences: ProjectLaunchServicePreferences;
  projectLaunchServiceStatus: ProjectLaunchServiceStatus;
  projectLaunchServiceLogRetentionStatus: ProjectLaunchServiceLogRetentionStatus;
  builtinEnvironmentTools: EnvironmentToolDefinition[];
  environmentResults: EnvironmentToolResult[];
  environmentChecked: boolean;
  environmentRefreshing: boolean;
  environmentRefreshingKeys: Record<string, boolean>;
  environmentRequestGenerations: Record<string, number>;
  environmentActiveRefreshes: number;
  aiPreferences: AiPreferences;
  aiModels: AiModelInfo[];
  aiModelRefreshing: boolean;
  aiModelRefreshMessage: string;
  aiModelTesting: boolean;
  aiModelTestMessage: string;
  aiModelTestOk: boolean;
  aiAnalyzing: boolean;
  aiAnalysisResult: string;
  aiAnalysisMessage: string;
  aiAnalysisState: AiAnalysisState;
  supportsBridge: boolean;
  projectsLoaded: boolean;
  projectStorageMessage: string;
  projectConfigMessage: string;
  projectFormInspectionMessage: string;
  projectFormInspecting: boolean;
  projectFormCwdSuggestions: string[];
  projectFormOpen: boolean;
  projectFormMode: "create" | "edit" | "duplicate";
  projectFormDraft: ProjectFormValue;
  pendingDeleteProjectId: string;
  uiPreferences: UiPreferences;
  activeIconPack: IconPackManifest;
  iconPackStatus: IconPackStatus;
  iconPackMessage: string;
  projects: Project[];
  selectedProjectId: string;
  workActivityPreferences: WorkActivityPreferences;
  workActivitySelectedProjectIds: string[];
  workActivitySelectionInitialized: boolean;
  workActivityUnavailableProjectIds: string[];
  workActivityReport: ProjectGitActivityReport;
  workActivityLoading: boolean;
  workActivityReportKey: string;
  workActivityReportExpiresAt: number;
  workActivityPendingKey: string;
  workActivityMessage: string;
  workActivityLoadState: "idle" | "loading" | "error" | "refreshing" | "ready" | "cached" | "partial" | "stale";
  workActivityRetryingRepositoryPaths: string[];
  workActivityRequestGeneration: number;
  workActivityDayRequestGeneration: number;
  workActivityReturnProjectId: string;
  workActivityFocusProjectId: string;
  automationActiveProjectRuns: Record<string, string>;
  automationNextTimerAt: string;
  projectDetailsTabRequest: { projectId: string; tab: "automation" | "git" | "memo"; requestedAt: number; commitHash?: string; };
  logs: Record<string, LogEntry[]>;
  scriptLogs: Record<string, Record<string, LogEntry[]>>;
  stagedFiles: Record<string, ProjectGitFileChange[]>;
  gitRefreshing: Record<string, boolean>;
  gitStatusRefreshing: Record<string, boolean>;
  gitRepositorySnapshots: Record<string, ProjectGitSnapshot>;
  gitRepositoryRefreshing: Record<string, boolean>;
  gitRepositoryStatusRefreshing: Record<string, boolean>;
  gitRepositoryReadFailures: Record<string, Partial<Record<ProjectGitReadOperation, ProjectGitReadFailure>>>;
  gitRepositoryLoadingMore: Record<string, boolean>;
  gitWritesInProgress: Record<string, number>;
  gitWorkspaces: Record<string, ProjectGitWorkspaceSnapshot>;
  gitWorkspaceRefreshing: Record<string, boolean>;
  todos: Record<string, TodoItem[]>;
  memoContent: Record<string, string>;
}

export interface AppGetters {
  visibleProjects(state: AppState): Project[];
  availableProjects(state: AppState): Project[];
  unavailableProjects(state: AppState): Project[];
  workActivitySelectableProjects(state: AppState): Project[];
  workActivitySelectedProjects(): Project[];
  selectedProject(state: AppState): Project;
  relatedProjectsFor(state: AppState): (projectId: string) => Project[];
  pendingDeleteProject(state: AppState): Project;
  hasActiveProjectLaunchServiceRuns(state: AppState): boolean;
  serviceAutomationTaskEntries(state: AppState): (projectId: string, taskId: string) => ProjectAutomationPlanEntry[];
  currentMessages(state: AppState): "zh-CN" | "en-US";
}

export interface AppActions {
  initializeProjectSessionState(): void;
  loadProjectLaunchServiceAutomationHistory(projectId: string, taskId: string): Promise<ProjectAutomationHistoryEntry[]>;
  reloadProjectsFromStorage(): Promise<void>;
  scheduleProjectCatalogReload(): Promise<void>;
  loadProjects(): Promise<void>;
  reconcileProjectLaunchServiceRuntime(status: ProjectLaunchServiceStatus): void;
  persistProjects(synchronizeProjectLaunchService?: boolean, removedProjectIds?: string[]): Promise<void>;
  refreshProjectAvailability(): Promise<void>;
  setLocale(locale: Locale): void;
  setTheme(theme: "auto" | "light" | "dark"): void;
  setIconPackColorMode(colorMode: IconPackColorMode): void;
  loadIconPack(): Promise<IconPackLoadResult>;
  setIconPack(packId: string): Promise<IconPackLoadResult>;
  checkIconPackUpdate(): Promise<IconPackUpdateResult>;
  installIconPack(): Promise<IconPackLoadResult>;
  verifyIconPackInstall(): Promise<IconPackLoadResult>;
  removeIconPack(): Promise<IconPackRemoveResult>;
  refreshProjectLaunchServiceStatus(verifyManualInstall?: boolean): Promise<any>;
  checkProjectLaunchServiceUpdate(): Promise<any>;
  loadProjectLaunchServiceRunLog(runId: string): Promise<{ logs: LogEntry[]; runId: string; events: ProjectLaunchServiceEvent[]; truncated: boolean; sizeBytes: number; hasMore?: boolean; nextOffset?: number; }>;
  loadProjectLaunchServiceRunLogPage(runId: string, beforeOffset: number): Promise<{ logs: LogEntry[]; runId: string; events: ProjectLaunchServiceEvent[]; truncated: boolean; sizeBytes: number; hasMore?: boolean; nextOffset?: number; }>;
  refreshProjectLaunchServiceLogRetention(): Promise<any>;
  updateProjectLaunchServiceLogRetention(policy: ProjectLaunchServiceLogRetentionPolicy): Promise<any>;
  listProjectLaunchServiceLogs(projectId: string): Promise<ProjectLaunchServiceLogDescriptor[]>;
  clearProjectLaunchServiceLogs(scope?: ProjectLaunchServiceLogClearScope): Promise<ProjectLaunchServiceLogClearResult>;
  downloadProjectLaunchService(): Promise<any>;
  openProjectLaunchServiceDirectory(): Promise<void>;
  openProjectLaunchServiceReleases(): Promise<void>;
  openIconPackDirectory(): Promise<void>;
  openIconPackReleases(): Promise<void>;
  synchronizeProjectLaunchServiceAutomation(): Promise<ProjectLaunchServiceAutomationSyncResult>;
  queueProjectLaunchServiceAutomationSync(): Promise<void>;
  synchronizeProjectLaunchServiceAutomationForUserAction(): Promise<boolean>;
  setProjectLaunchServiceEnabled(enabled: boolean): Promise<any>;
  setProjectDetailsTabOrder(order: ("automation" | "git" | "memo" | "info" | "scripts" | "files")[]): void;
  setProjectDetailsDefaultTab(tab: "automation" | "git" | "memo" | "info" | "scripts" | "files"): void;
  setTinyCardActionTrigger(trigger: TinyCardActionTrigger): void;
  acknowledgeProjectDetailsTabReorderHint(version: number): void;
  acknowledgeProjectDetailsTabDefaultHint(version: number): void;
  setProjectConfigMessage(message: string): void;
  setDefaultTerminal(kind: DefaultTerminalKind): void;
  setDefaultTerminalCustomCommand(command: string): void;
  persistExternalApplicationPreferences(preferences: ExternalApplicationPreferences): void;
  addExternalApplication(name: string, command: string): boolean;
  updateExternalApplication(id: string, name: string, command: string): boolean;
  setExternalApplicationEnabled(id: string, enabled: boolean): boolean;
  deleteExternalApplication(id: string): boolean;
  setDefaultExternalApplication(id: string): boolean;
  restoreExternalApplicationNativeLaunch(id: string): boolean;
  setEnvironmentToolEnabled(key: EnvironmentToolKey, enabled: boolean): void;
  invalidateEnvironmentTool(key: string): void;
  addCustomEnvironmentTool(input: CustomEnvironmentToolInput): { ok: false; errors: Partial<Record<keyof CustomEnvironmentToolInput, string>>; tool?: undefined; } | { ok: true; tool: CustomEnvironmentTool; errors?: undefined; };
  updateCustomEnvironmentTool(id: string, input: CustomEnvironmentToolInput): { ok: false; errors: Partial<Record<keyof CustomEnvironmentToolInput, string>>; tool?: undefined; } | { ok: true; tool: any; errors?: undefined; };
  setCustomEnvironmentToolEnabled(id: string, enabled: boolean): void;
  deleteCustomEnvironmentTool(id: string): void;
  saveBuiltinEnvironmentToolOverride(key: EnvironmentToolKey, input: Pick<CustomEnvironmentToolInput, "command" | "versionArgs">): { ok: false; errors: Partial<Record<keyof CustomEnvironmentToolInput, string>>; override?: undefined; } | { ok: true; override: BuiltinEnvironmentToolOverride; errors?: undefined; };
  restoreBuiltinEnvironmentTool(key: EnvironmentToolKey): void;
  refreshEnvironmentTools(targetKeys?: string[]): Promise<void>;
  setAiPreferences(patch: Partial<AiPreferences>): void;
  addAiPromptMode(): string;
  updateAiPromptMode(modeId: string, patch: Partial<Pick<AiPromptMode, "name" | "prompt">>): void;
  deleteAiPromptMode(modeId: string): void;
  resetAiPromptModes(): void;
  refreshAiModels(): Promise<void>;
  testAiConfiguration(): Promise<AiModelTestResult>;
  analyzeGitWithAiStream(projectId: string, prompt: string, handlers?: AiStreamHandlers): Promise<AiAnalyzeResult>;
  analyzeGitWithAi(projectId: string, prompt: string): Promise<void>;
  setActiveTab(tab: "projects" | "settings" | "environment" | "activity"): void;
  openWorkActivity(projectId?: string): void;
  returnFromWorkActivity(): void;
  setWorkActivityProjectIds(projectIds: string[]): void;
  saveWorkActivityProjectGroup(name: string): boolean;
  applyWorkActivityProjectGroup(groupId: string): boolean;
  clearWorkActivityProjectFocus(): boolean;
  renameWorkActivityProjectGroup(groupId: string, name: string): boolean;
  deleteWorkActivityProjectGroup(groupId: string): boolean;
  invalidateWorkActivity(): void;
  setWorkActivityPreferences(preferences: Partial<WorkActivityPreferences>): void;
  loadGitActivity(options: ProjectGitActivityOptions): Promise<void>;
  retryWorkActivityRepository(repositoryPath: string, options: ProjectGitActivityOptions): Promise<boolean>;
  readGitActivityChanges(options: ProjectGitActivityChangesOptions, projectPaths?: string[]): Promise<ProjectGitActivityChangesReport>;
  readGitActivityDay(options: ProjectGitActivityDayOptions, projectPaths?: string[]): Promise<ProjectGitActivityDayReport>;
  setSelectedProject(id: string): void;
  openProjectByName(query: string): boolean;
  openCreateProjectForm(): void;
  openEditProjectForm(projectId: string): void;
  openDuplicateProjectForm(projectId: string): void;
  closeProjectForm(): void;
  updateProjectForm(patch: Partial<ProjectFormValue>): void;
  inspectCurrentProjectPath(): Promise<void>;
  discoverProjectFormScripts(sources: ProjectScriptDiscoverySource[]): Promise<ProjectBridgeScriptCandidate[]>;
  importProjectFormScripts(candidates: ProjectBridgeScriptCandidate[]): number;
  refreshProjectFormCwdSuggestions(projectPath?: string): Promise<void>;
  pickProjectPath(): Promise<void>;
  pickQuickLinkPath(): Promise<void>;
  addEnvironmentEntry(): void;
  updateEnvironmentEntry(entryId: string, patch: Partial<ProjectEnvironmentEntry>): void;
  removeEnvironmentEntry(entryId: string): void;
  addScriptEntry(): void;
  updateScriptEntry(scriptId: string, patch: Partial<ProjectScriptFormValue>): void;
  removeScriptEntry(scriptId: string): void;
  moveScriptEntry(scriptId: string, direction: "up" | "down"): void;
  reorderScriptEntry(scriptId: string, targetScriptId: string): void;
  reorderProjectScripts(projectId: string, scriptId: string, targetScriptId: string): boolean;
  saveProjectForm(): Promise<string>;
  deleteProject(projectId: string): Promise<boolean>;
  requestDeleteProject(projectId: string): void;
  cancelDeleteProject(): void;
  confirmDeleteProject(): Promise<any>;
  refreshProjectScripts(projectId: string): Promise<void>;
  refreshProjects(): Promise<void>;
  refreshDashboardGitChangeCounts(): Promise<void>;
  moveProject(projectId: string, direction: "up" | "down" | "top", scopeProjectIds?: string[]): Promise<boolean>;
  reorderProject(projectId: string, targetProjectId: string, scopeProjectIds?: string[], position?: "before" | "after"): Promise<boolean>;
  resolveGitRepositoryContext(projectId: string, target?: ProjectGitRepositoryTarget): ProjectGitRepositoryContext;
  gitSnapshotForRepository(projectId: string, target?: ProjectGitRepositoryTarget): ProjectGitSnapshot;
  refreshGitSnapshot(projectId: string, options?: { force?: boolean; maxAgeMs?: number; limit?: number; }, target?: ProjectGitRepositoryTarget): Promise<void>;
  refreshGitWorkspace(projectId: string, options?: { force?: boolean; }): Promise<void>;
  refreshGitWorkingTreeSnapshot(projectId: string, target?: ProjectGitRepositoryTarget): Promise<void>;
  refreshGitStatusSnapshot(projectId: string, target?: ProjectGitRepositoryTarget): Promise<void>;
  refreshGitSnapshotForInteraction(projectId: string, target?: ProjectGitRepositoryTarget, options?: { maxAgeMs?: number; limit?: number; }): Promise<void>;
  loadMoreGitCommits(projectId: string, target?: ProjectGitRepositoryTarget): Promise<void>;
  listProjectFiles(projectId: string, relativePath?: string): Promise<ProjectFileListResult>;
  searchProjectFiles(projectId: string, query: string, options?: { limit?: number; }): Promise<ProjectFileSearchResult>;
  createProjectEntry(projectId: string, parentRelativePath: string, name: string, kind: ProjectFileKind): Promise<ProjectFileMutationResult>;
  renameProjectEntry(projectId: string, relativePath: string, name: string): Promise<ProjectFileMutationResult>;
  deleteProjectEntry(projectId: string, relativePath: string): Promise<ProjectFileMutationResult>;
  showProjectEntryInFolder(projectId: string, relativePath: string): Promise<void>;
  readProjectFile(projectId: string, relativePath: string): Promise<ProjectFileReadResult>;
  readGitFileDiff(projectId: string, relativePath: string, options?: ProjectGitFileDiffOptions, target?: ProjectGitRepositoryTarget): Promise<ProjectGitFileDiffResult>;
  readGitCommitFileDiff(projectId: string, commitHash: string, relativePath: string, target?: ProjectGitRepositoryTarget, stash?: ProjectGitStash, options?: ProjectGitFileDiffOptions): Promise<ProjectGitFileDiffResult>;
  readGitCommitFiles(projectId: string, commitHash: string, target?: ProjectGitRepositoryTarget, stash?: ProjectGitStash): Promise<ProjectGitFileChange[]>;
  readGitTagInfo(projectId: string, tagName: string, target?: ProjectGitRepositoryTarget): Promise<ProjectGitTagInfo>;
  readGitCommitAuthorAvatar(projectId: string, commitHash: string, target?: ProjectGitRepositoryTarget): Promise<string>;
  readGitCommitMessageDiff(projectId: string, target?: ProjectGitRepositoryTarget): Promise<ProjectGitCommitMessageDiffResult>;
  initializeGitRepository(projectId: string): Promise<ProjectGitActionResult>;
  runAuthorizedGitWrite<TResult extends ProjectGitActionResult>(projectId: string, target: ProjectGitRepositoryTarget, action: (context: ProjectGitRepositoryContext) => Promise<TResult>, options: { refresh: "status" | "working-tree" | "full"; refs?: boolean; refreshOnFailure?: boolean; }): Promise<TResult>;
  stageGitFile(projectId: string, relativePath: string, target?: ProjectGitRepositoryTarget): Promise<ProjectGitActionResult>;
  unstageGitFile(projectId: string, relativePath: string, target?: ProjectGitRepositoryTarget): Promise<ProjectGitActionResult>;
  discardGitFile(projectId: string, relativePath: string, target?: ProjectGitRepositoryTarget): Promise<ProjectGitActionResult>;
  stageGitFiles(projectId: string, relativePaths: string[], options?: { all?: boolean; }, target?: ProjectGitRepositoryTarget): Promise<ProjectGitActionResult>;
  unstageGitFiles(projectId: string, relativePaths: string[], options?: { all?: boolean; }, target?: ProjectGitRepositoryTarget): Promise<ProjectGitActionResult>;
  discardGitFiles(projectId: string, relativePaths: string[], options?: { all?: boolean; }, target?: ProjectGitRepositoryTarget): Promise<ProjectGitActionResult>;
  commitGitStaged(projectId: string, message: string, target?: ProjectGitRepositoryTarget): Promise<ProjectGitActionResult>;
  amendGitCommit(projectId: string, message: string, target?: ProjectGitRepositoryTarget): Promise<ProjectGitActionResult>;
  undoLastGitCommit(projectId: string, options?: { allowMerge?: boolean; }, target?: ProjectGitRepositoryTarget): Promise<ProjectGitActionResult>;
  cherryPickGitCommit(projectId: string, commitHash: string, target?: ProjectGitRepositoryTarget): Promise<ProjectGitActionResult>;
  revertGitCommit(projectId: string, commitHash: string, target?: ProjectGitRepositoryTarget): Promise<ProjectGitActionResult>;
  createGitStash(projectId: string, message?: string, options?: ProjectGitStashOptions, target?: ProjectGitRepositoryTarget): Promise<ProjectGitActionResult>;
  applyGitStash(projectId: string, stashRef: string, target?: ProjectGitRepositoryTarget): Promise<ProjectGitActionResult>;
  popGitStash(projectId: string, stashRef: string, target?: ProjectGitRepositoryTarget): Promise<ProjectGitActionResult>;
  dropGitStash(projectId: string, stashRef: string, target?: ProjectGitRepositoryTarget): Promise<ProjectGitActionResult>;
  switchGitBranch(projectId: string, branchName: string, options?: { force?: boolean; }, target?: ProjectGitRepositoryTarget): Promise<ProjectGitActionResult>;
  checkoutGitCommit(projectId: string, commitHash: string, options?: { force?: boolean; detach?: boolean; }, target?: ProjectGitRepositoryTarget): Promise<ProjectGitActionResult>;
  createGitBranch(projectId: string, branchName: string, commitHash: string, options?: { checkout?: boolean; force?: boolean; }, target?: ProjectGitRepositoryTarget): Promise<ProjectGitActionResult>;
  createGitTag(projectId: string, tagName: string, commitHash: string, options?: { annotated?: boolean; message?: string; }, target?: ProjectGitRepositoryTarget): Promise<ProjectGitActionResult>;
  deleteGitTag(projectId: string, tagName: string, target?: ProjectGitRepositoryTarget): Promise<ProjectGitActionResult>;
  pushGitTag(projectId: string, tagName: string, remoteName?: string, target?: ProjectGitRepositoryTarget): Promise<ProjectGitActionResult>;
  renameGitBranch(projectId: string, branchName: string, nextBranchName: string, target?: ProjectGitRepositoryTarget): Promise<ProjectGitActionResult>;
  deleteGitBranch(projectId: string, branchName: string, options?: { force?: boolean; }, target?: ProjectGitRepositoryTarget): Promise<ProjectGitActionResult>;
  checkoutGitRemoteBranch(projectId: string, remoteRef: string, options?: { force?: boolean; }, target?: ProjectGitRepositoryTarget): Promise<ProjectGitActionResult>;
  fetchGitRemote(projectId: string, target?: ProjectGitRepositoryTarget): Promise<ProjectGitActionResult>;
  fetchGitRemoteByName(projectId: string, remoteName: string, target?: ProjectGitRepositoryTarget): Promise<ProjectGitActionResult>;
  pullGitRemote(projectId: string, target?: ProjectGitRepositoryTarget): Promise<ProjectGitActionResult>;
  pushGitRemote(projectId: string, target?: ProjectGitRepositoryTarget, options?: ProjectGitPushOptions): Promise<ProjectGitActionResult>;
  mergeGitBaseBranch(projectId: string, target?: ProjectGitRepositoryTarget): Promise<ProjectGitMergeResult>;
  abortGitMerge(projectId: string, target?: ProjectGitRepositoryTarget): Promise<ProjectGitActionResult>;
  publishGitBranch(projectId: string, remoteName: string, target?: ProjectGitRepositoryTarget): Promise<ProjectGitActionResult>;
  addGitRemote(projectId: string, remoteName: string, remoteUrl: string, target?: ProjectGitRepositoryTarget): Promise<ProjectGitActionResult>;
  setGitRemoteUrl(projectId: string, remoteName: string, remoteUrl: string, target?: ProjectGitRepositoryTarget): Promise<ProjectGitActionResult>;
  removeGitRemote(projectId: string, remoteName: string, target?: ProjectGitRepositoryTarget): Promise<ProjectGitActionResult>;
  deleteGitRemoteBranch(projectId: string, remoteName: string, branchName: string, target?: ProjectGitRepositoryTarget): Promise<ProjectGitActionResult>;
  writeProjectFile(projectId: string, relativePath: string, content: string): Promise<ProjectFileWriteResult>;
  automationTaskValidation(projectId: string, task: ProjectAutomationTask): { valid: boolean; message: string; };
  scheduleAutomationTimer(): void;
  markMissedAutomationPlans(notify?: boolean): void;
  reconcileOrphanedAutomationRuns(): Promise<boolean>;
  reconcileRuntimeProcessState(): Promise<void>;
  runDueAutomationPlans(notifyMissed?: boolean): Promise<void>;
  recomputeAutomationPlans(projectId?: string, notifyMissed?: boolean): void;
  createAutomationTask(projectId: string, patch: Partial<ProjectAutomationTask>): { ok: boolean; message: any; task?: undefined; } | { ok: boolean; message: string; task: ProjectAutomationTask; };
  duplicateAutomationTask(projectId: string, taskId: string, name: string): { ok: boolean; message: any; task?: undefined; } | { ok: boolean; message: string; task: ProjectAutomationTask; };
  updateAutomationTask(projectId: string, taskId: string, patch: Partial<ProjectAutomationTask>): { ok: boolean; message: any; task?: undefined; } | { ok: boolean; message: string; task: any; };
  deleteAutomationTask(projectId: string, taskId: string): boolean;
  openProjectAutomation(projectId: string): void;
  openProjectMemo(projectId: string): void;
  openProjectGit(projectId: string, commitHash?: string): void;
  finishAutomationPlanEntry(project: Project, task: ProjectAutomationTask, entry: ProjectAutomationPlanEntry, status: ProjectAutomationHistoryStatus, reason: string, scriptResults: ProjectAutomationScriptResult[], runId?: string, notify?: boolean): void;
  runAutomationTask(projectId: string, taskId: string, entryId: string): Promise<void>;
  runAutomationPlanEntryEarly(projectId: string, taskId: string, entryId: string): Promise<boolean>;
  runAutomationTaskNow(projectId: string, taskId: string): Promise<boolean>;
  ignoreMissedAutomationTask(projectId: string, taskId: string): Promise<boolean>;
  runAutomationScript(projectId: string, scriptId: string, automationRunId: string, steps: ProjectAutomationInputStep[], exitConfig: ProjectAutomationExitConfig, maxRuntimeMinutes: number, continueAfterInput: boolean): Promise<ProjectAutomationScriptResult>;
  sendAutomationInput(context: AutomationScriptRuntimeContext, value: string): Promise<boolean>;
  advanceAutomationInputStep(context: AutomationScriptRuntimeContext): void;
  consumeAutomationOutputMatch(context: AutomationScriptRuntimeContext): Promise<void>;
  handleAutomationBridgeEvent(event: ProjectBridgeEvent): void;
  launchScript(projectId: string, scriptId: string, automationRunId?: string): Promise<ProjectBridgeRunResult>;
  launchAllScripts(projectId: string): Promise<any[]>;
  stopScript(projectId: string, scriptId: string, stopOptions?: ProjectBridgeStopProcessOptions): Promise<void>;
  stopRunningScriptsForPluginExit(): void;
  sendScriptInput(projectId: string, scriptId: string, input: string): Promise<ProjectBridgeSendInputResult>;
  openProjectFolder(projectId: string): Promise<void>;
  showGitRepositoryInFolder(projectId: string, target: ProjectGitRepositoryTarget): Promise<void>;
  openGitRepositoryInTerminal(projectId: string, target: ProjectGitRepositoryTarget): Promise<void>;
  openGitRepositoryInEditor(projectId: string, target: ProjectGitRepositoryTarget, applicationId?: string): Promise<void>;
  openProjectInTerminal(projectId: string): Promise<void>;
  openProjectInEditor(projectId: string, applicationId?: string): Promise<void>;
  openProjectQuickLink(projectId: string): Promise<void>;
  addLog(projectId: string, log: LogEntry, scriptId?: string): void;
  clearLogs(projectId: string): void;
  clearScriptLogs(projectId: string, scriptId: string): void;
  addTodo(projectId: string, text: string): void;
  toggleTodo(projectId: string, todoId: string): void;
  updateTodo(projectId: string, todoId: string, text: string): void;
  deleteTodo(projectId: string, todoId: string): void;
  reorderTodo(projectId: string, todoId: string, targetTodoId: string): void;
  syncProjectTodos(projectId: string): void;
  updateMemo(projectId: string, content: string): void;
  exportProjectConfig(): Promise<void>;
  importProjectConfig(): Promise<void>;
  handleBridgeEvent(event: ProjectBridgeEvent): void;
}

export type AppStore = Store<"app", AppState, AppGetters, AppActions>;
